// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "Wallet API",
    "version": "1.0",
    "description": "Comprehensive Wallet Backend API for Member, Trade, Transfer, Chat, and Agent Services",
    "contact": {
      "name": "API Support"
    }
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "Format: Bearer {token}"
    }
  },
  "tags": [
    {
      "name": "member",
      "description": "Member account operations"
    },
    {
      "name": "transfer",
      "description": "Member transfer operations"
    },
    {
      "name": "trade",
      "description": "C2C trading operations"
    },
    {
      "name": "chat",
      "description": "Chat and messaging operations"
    },
    {
      "name": "notify",
      "description": "Notification operations"
    },
    {
      "name": "agent",
      "description": "Agent role management"
    }
  ],
  "paths": {
    "/member/send-sms": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Send SMS code",
        "description": "Send SMS verification code to phone number",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "purpose": {
                  "type": "integer",
                  "example": 1,
                  "description": "SMS purpose code"
                },
                "area": {
                  "type": "string",
                  "example": "+86",
                  "description": "Area code"
                },
                "number": {
                  "type": "string",
                  "example": "13800138000",
                  "description": "Phone number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "example": 0
                },
                "msg": {
                  "type": "string",
                  "example": "success"
                },
                "data": {
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "msg": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/member/register": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Register new member",
        "description": "Register a new member account",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "account": {
                  "type": "string",
                  "example": "user@example.com"
                },
                "password": {
                  "type": "string",
                  "example": "password123"
                },
                "area_code": {
                  "type": "string",
                  "example": "+86"
                },
                "phone": {
                  "type": "string",
                  "example": "13800138000"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "msg": {
                  "type": "string"
                },
                "data": {
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/login": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Member login",
        "description": "Login to member account",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "account": {
                  "type": "string",
                  "example": "user@example.com"
                },
                "password": {
                  "type": "string",
                  "example": "password123"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "msg": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "account": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/reset-pwd": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Reset password",
        "description": "Reset member password using SMS code",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "area_code": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "sms_code": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/change-pwd": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Change password",
        "description": "Change member password",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "hash": {
                  "type": "string"
                },
                "area_code": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/profile": {
      "get": {
        "tags": [
          "member"
        ],
        "summary": "Get member profile",
        "description": "Get authenticated member profile",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "msg": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "account": {
                      "type": "string"
                    },
                    "nickname": {
                      "type": "string"
                    },
                    "status": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/member/assets": {
      "get": {
        "tags": [
          "member"
        ],
        "summary": "Get member assets",
        "description": "Get authenticated member wallet assets",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "msg": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "currency": {
                      "type": "string"
                    },
                    "free": {
                      "type": "string"
                    },
                    "cny": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/member/change-nickname": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Change nickname",
        "description": "Change member nickname",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "new_nickname": {
                  "type": "string",
                  "example": "小王"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/phone/verify": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Verify phone number",
        "description": "Verify phone number for binding",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "area_code": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/phone/bind": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Bind phone number",
        "description": "Bind phone number to member account",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "area_code": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "sms_code": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/pin/commit": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Set up or update PIN",
        "description": "Commit new PIN for member account",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "old_pin": {
                  "type": "string"
                },
                "new_pin": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/pin/reset": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Reset PIN",
        "description": "Reset PIN using SMS verification",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "area_code": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "sms_code": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/pin/change": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Change PIN",
        "description": "Change member PIN with verification hash",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "hash": {
                  "type": "string"
                },
                "new_pin": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/payment/method/list": {
      "get": {
        "tags": [
          "member"
        ],
        "summary": "Get payment methods list",
        "description": "Get list of member payment methods",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/member/payment/method/add": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Add payment method",
        "description": "Add a new payment method for member",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string",
                  "example": "BANKCARD",
                  "description": "Payment method code (BANKCARD, WEPAY, ALIPAY, ECNY)"
                },
                "member_name": {
                  "type": "string",
                  "example": "张三"
                },
                "account": {
                  "type": "string",
                  "example": "6225123456789012"
                },
                "bank": {
                  "type": "string",
                  "example": "中国银行"
                },
                "branch": {
                  "type": "string",
                  "example": "北京分行"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/payment/method/del": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Delete payment method",
        "description": "Delete a payment method from member",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/member/payment/method/set-def": {
      "post": {
        "tags": [
          "member"
        ],
        "summary": "Set default payment method",
        "description": "Set a payment method as default for member",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/transfer/preflight": {
      "post": {
        "tags": [
          "transfer"
        ],
        "summary": "Transfer preflight check",
        "description": "Check transfer prerequisites and generate order number",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "msg": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "member_status": {
                      "type": "integer"
                    },
                    "has_pin": {
                      "type": "boolean"
                    },
                    "free": {
                      "type": "string"
                    },
                    "frozen": {
                      "type": "string"
                    },
                    "order_no": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/transfer/resolve": {
      "get": {
        "tags": [
          "transfer"
        ],
        "summary": "Resolve payee code",
        "description": "Resolve payee information from payee code",
        "parameters": [
          {
            "in": "query",
            "name": "p",
            "required": true,
            "type": "string",
            "description": "Payee code"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "payee_status": {
                      "type": "integer"
                    },
                    "display": {
                      "type": "string"
                    },
                    "payee_id": {
                      "type": "integer"
                    },
                    "payee_code": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/transfer/confirm": {
      "post": {
        "tags": [
          "transfer"
        ],
        "summary": "Confirm transfer",
        "description": "Confirm and execute member transfer",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "order_no": {
                  "type": "string"
                },
                "payee": {
                  "type": "integer"
                },
                "payee_code": {
                  "type": "string"
                },
                "currency": {
                  "type": "string"
                },
                "amount": {
                  "type": "string"
                },
                "desc": {
                  "type": "string"
                },
                "pin": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/transfer/checkout/resolve": {
      "get": {
        "tags": [
          "transfer"
        ],
        "summary": "Resolve checkout token",
        "description": "Resolve merchant checkout token information",
        "parameters": [
          {
            "in": "query",
            "name": "t",
            "required": true,
            "type": "string",
            "description": "Checkout token"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/transfer/checkout/confirm": {
      "post": {
        "tags": [
          "transfer"
        ],
        "summary": "Confirm checkout payment",
        "description": "Confirm and execute merchant checkout payment",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "type": "string"
                },
                "pin": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/price": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get C2C price",
        "description": "Get current C2C trading price",
        "parameters": [
          {
            "in": "query",
            "name": "currency",
            "required": true,
            "type": "string",
            "description": "Currency code"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "data": {
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/ads/list": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get C2C advertisements list",
        "description": "Get list of C2C advertisements",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "offset",
            "type": "string",
            "description": "Offset"
          },
          {
            "in": "query",
            "name": "limit",
            "type": "integer",
            "description": "Limit"
          },
          {
            "in": "query",
            "name": "side",
            "type": "integer",
            "description": "Side (1=buy, 2=sell)"
          },
          {
            "in": "query",
            "name": "currency",
            "type": "string",
            "description": "Currency code"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/ads/detail": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get C2C advertisement detail",
        "description": "Get detailed information of a C2C advertisement",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "required": true,
            "type": "integer",
            "description": "Advertisement ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/ads/create": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Create C2C advertisement",
        "description": "Create a new C2C advertisement",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "price": {
                  "type": "string"
                },
                "total": {
                  "type": "string"
                },
                "min_count": {
                  "type": "string"
                },
                "max_count": {
                  "type": "string"
                },
                "pay_methods": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/ads/pause": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Pause C2C advertisement",
        "description": "Pause an active C2C advertisement",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "ads_id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/ads/publish": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Publish C2C advertisement",
        "description": "Publish a paused C2C advertisement",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "ads_id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/ads/cancel": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Cancel C2C advertisement",
        "description": "Cancel a C2C advertisement",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "ads_id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/ads/my-list": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get my C2C advertisements",
        "description": "Get list of my C2C advertisements",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "description": "Page number"
          },
          {
            "in": "query",
            "name": "page_size",
            "type": "integer",
            "description": "Page size"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/detail": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get C2C order detail",
        "description": "Get detailed information of a C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "type": "integer",
            "description": "Order ID (primary key)"
          },
          {
            "in": "query",
            "name": "order_id",
            "type": "string",
            "description": "Order ID (order number)"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/create": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Create C2C order",
        "description": "Create a new C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "ads_id": {
                  "type": "integer"
                },
                "total": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/agree": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Agree C2C order",
        "description": "Agree to a C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "order_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/cancel": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Cancel C2C order",
        "description": "Cancel a C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "order_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/pay": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Pay C2C order",
        "description": "Pay for a C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "order_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/pay-cert": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Confirm C2C order payment",
        "description": "Confirm payment for a C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "order_id": {
                  "type": "string"
                },
                "type": {
                  "type": "integer"
                },
                "bank_msg_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/send": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Send C2C order",
        "description": "Send (release) crypto for a C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "order_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/unusual": {
      "post": {
        "tags": [
          "trade"
        ],
        "summary": "Report unusual C2C order",
        "description": "Report an unusual C2C order",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "order_id": {
                  "type": "string"
                },
                "reason": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/history": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get C2C order history",
        "description": "Get history of C2C orders",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "description": "Page number"
          },
          {
            "in": "query",
            "name": "page_size",
            "type": "integer",
            "description": "Page size"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/order/my-list": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get my C2C orders",
        "description": "Get list of my C2C orders",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "description": "Page number"
          },
          {
            "in": "query",
            "name": "page_size",
            "type": "integer",
            "description": "Page size"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/trade/c2c/price/list": {
      "get": {
        "tags": [
          "trade"
        ],
        "summary": "Get C2C price list",
        "description": "Get list of C2C prices",
        "responses": {
          "200": {
            "description": "Success"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/chat/ticket": {
      "post": {
        "tags": [
          "chat"
        ],
        "summary": "Get chat ticket",
        "description": "Get WebSocket connection ticket for chat",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "msg": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "ticket": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/chat/history": {
      "post": {
        "tags": [
          "chat"
        ],
        "summary": "Get chat history",
        "description": "Get chat message history for a session",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "session_id": {
                  "type": "string"
                },
                "last_msg_id": {
                  "type": "integer"
                },
                "size": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/chat/upload": {
      "post": {
        "tags": [
          "chat"
        ],
        "summary": "Upload chat image",
        "description": "Upload image for chat session",
        "security": [
          {
            "Bearer": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "in": "formData",
            "name": "session_id",
            "required": true,
            "type": "string"
          },
          {
            "in": "formData",
            "name": "image",
            "required": true,
            "type": "file"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "url": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/chat/upload-proof": {
      "post": {
        "tags": [
          "chat"
        ],
        "summary": "Upload transaction proof image",
        "description": "Upload transaction proof image for chat session",
        "security": [
          {
            "Bearer": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "in": "formData",
            "name": "session_id",
            "required": true,
            "type": "string"
          },
          {
            "in": "formData",
            "name": "image",
            "required": true,
            "type": "file"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "url": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/notify/sync": {
      "get": {
        "tags": [
          "notify"
        ],
        "summary": "Sync notifications",
        "description": "Synchronize all unread notifications for member",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "data": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/notify/ack": {
      "post": {
        "tags": [
          "notify"
        ],
        "summary": "Acknowledge notification",
        "description": "Mark notification as read",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "kind": {
                  "type": "integer",
                  "example": 1
                },
                "msg_id": {
                  "type": "integer"
                },
                "scope": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/agent/preflight": {
      "get": {
        "tags": [
          "agent"
        ],
        "summary": "Agent application preflight check",
        "description": "Check prerequisites for agent application",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "data": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/agent/apply": {
      "post": {
        "tags": [
          "agent"
        ],
        "summary": "Apply for agent",
        "description": "Apply to become an agent",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "pin": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/agent/refund": {
      "post": {
        "tags": [
          "agent"
        ],
        "summary": "Refund agent role",
        "description": "Refund agent role and return to regular member",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "pin": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "msg": {
          "type": "string"
        }
      }
    },
    "SuccessResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "msg": {
          "type": "string"
        },
        "data": {
          "type": "object"
        }
      }
    }
  }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{"http", "https"},
	Title:       "Wallet API",
	Description: "Comprehensive Wallet Backend API for Member, Trade, Transfer, Chat, and Agent Services",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

func init() {
	swag.Register(swag.Name, &s{})
}
